/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Kicker, KickerInterface } from "../../cat.sol/Kicker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "urn",
        type: "address",
      },
      {
        internalType: "address",
        name: "gal",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tab",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lot",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bid",
        type: "uint256",
      },
    ],
    name: "kick",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Kicker__factory {
  static readonly abi = _abi;
  static createInterface(): KickerInterface {
    return new Interface(_abi) as KickerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Kicker {
    return new Contract(address, _abi, runner) as unknown as Kicker;
  }
}
