/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CatLike } from "./CatLike";
export type { ClipLike } from "./ClipLike";
export type { DogLike } from "./DogLike";
export type { FlipLike } from "./FlipLike";
export type { GemInfo } from "./GemInfo";
export type { IlkRegistry } from "./IlkRegistry";
export type { JoinLike } from "./JoinLike";
export type { SpotLike } from "./SpotLike";
export type { TokenLike } from "./TokenLike";
export type { VatLike } from "./VatLike";
