/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PauseLike,
  PauseLikeInterface,
} from "../../DssSpell.sol/PauseLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class PauseLike__factory {
  static readonly abi = _abi;
  static createInterface(): PauseLikeInterface {
    return new Interface(_abi) as PauseLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PauseLike {
    return new Contract(address, _abi, runner) as unknown as PauseLike;
  }
}
