/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FlapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beg"
      | "bids"
      | "cage"
      | "deal"
      | "deny"
      | "file"
      | "fill"
      | "gem"
      | "kick"
      | "kicks"
      | "lid"
      | "live"
      | "rely"
      | "tau"
      | "tend"
      | "tick"
      | "ttl"
      | "vat"
      | "wards"
      | "yank"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Kick"): EventFragment;

  encodeFunctionData(functionFragment: "beg", values?: undefined): string;
  encodeFunctionData(functionFragment: "bids", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "cage", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "deal", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "deny", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "file",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fill", values?: undefined): string;
  encodeFunctionData(functionFragment: "gem", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kick",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "kicks", values?: undefined): string;
  encodeFunctionData(functionFragment: "lid", values?: undefined): string;
  encodeFunctionData(functionFragment: "live", values?: undefined): string;
  encodeFunctionData(functionFragment: "rely", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "tau", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tend",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tick", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "ttl", values?: undefined): string;
  encodeFunctionData(functionFragment: "vat", values?: undefined): string;
  encodeFunctionData(functionFragment: "wards", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "yank", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "beg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deny", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "file", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fill", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kicks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "live", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rely", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tau", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ttl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yank", data: BytesLike): Result;
}

export namespace KickEvent {
  export type InputTuple = [
    id: BigNumberish,
    lot: BigNumberish,
    bid: BigNumberish
  ];
  export type OutputTuple = [id: bigint, lot: bigint, bid: bigint];
  export interface OutputObject {
    id: bigint;
    lot: bigint;
    bid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Flapper extends BaseContract {
  connect(runner?: ContractRunner | null): Flapper;
  waitForDeployment(): Promise<this>;

  interface: FlapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beg: TypedContractMethod<[], [bigint], "view">;

  bids: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint] & {
        bid: bigint;
        lot: bigint;
        guy: string;
        tic: bigint;
        end: bigint;
      }
    ],
    "view"
  >;

  cage: TypedContractMethod<[rad: BigNumberish], [void], "nonpayable">;

  deal: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  deny: TypedContractMethod<[usr: AddressLike], [void], "nonpayable">;

  file: TypedContractMethod<
    [what: BytesLike, data: BigNumberish],
    [void],
    "nonpayable"
  >;

  fill: TypedContractMethod<[], [bigint], "view">;

  gem: TypedContractMethod<[], [string], "view">;

  kick: TypedContractMethod<
    [lot: BigNumberish, bid: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  kicks: TypedContractMethod<[], [bigint], "view">;

  lid: TypedContractMethod<[], [bigint], "view">;

  live: TypedContractMethod<[], [bigint], "view">;

  rely: TypedContractMethod<[usr: AddressLike], [void], "nonpayable">;

  tau: TypedContractMethod<[], [bigint], "view">;

  tend: TypedContractMethod<
    [id: BigNumberish, lot: BigNumberish, bid: BigNumberish],
    [void],
    "nonpayable"
  >;

  tick: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  ttl: TypedContractMethod<[], [bigint], "view">;

  vat: TypedContractMethod<[], [string], "view">;

  wards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  yank: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beg"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint] & {
        bid: bigint;
        lot: bigint;
        guy: string;
        tic: bigint;
        end: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cage"
  ): TypedContractMethod<[rad: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deal"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deny"
  ): TypedContractMethod<[usr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "file"
  ): TypedContractMethod<
    [what: BytesLike, data: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fill"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gem"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "kick"
  ): TypedContractMethod<
    [lot: BigNumberish, bid: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "kicks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "live"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rely"
  ): TypedContractMethod<[usr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tau"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tend"
  ): TypedContractMethod<
    [id: BigNumberish, lot: BigNumberish, bid: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tick"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ttl"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vat"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "yank"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Kick"
  ): TypedContractEvent<
    KickEvent.InputTuple,
    KickEvent.OutputTuple,
    KickEvent.OutputObject
  >;

  filters: {
    "Kick(uint256,uint256,uint256)": TypedContractEvent<
      KickEvent.InputTuple,
      KickEvent.OutputTuple,
      KickEvent.OutputObject
    >;
    Kick: TypedContractEvent<
      KickEvent.InputTuple,
      KickEvent.OutputTuple,
      KickEvent.OutputObject
    >;
  };
}
