/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OracleLike,
  OracleLikeInterface,
} from "../../../src/DssAction.sol/OracleLike";

const _abi = [
  {
    inputs: [],
    name: "src",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class OracleLike__factory {
  static readonly abi = _abi;
  static createInterface(): OracleLikeInterface {
    return new Interface(_abi) as OracleLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OracleLike {
    return new Contract(address, _abi, runner) as unknown as OracleLike;
  }
}
