/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Changelog,
  ChangelogInterface,
} from "../../../src/DssExec.sol/Changelog";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "getAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Changelog__factory {
  static readonly abi = _abi;
  static createInterface(): ChangelogInterface {
    return new Interface(_abi) as ChangelogInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Changelog {
    return new Contract(address, _abi, runner) as unknown as Changelog;
  }
}
