/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PauseAbstract,
  PauseAbstractInterface,
} from "../../../src/DssExec.sol/PauseAbstract";

const _abi = [
  {
    inputs: [],
    name: "delay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "exec",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "plot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class PauseAbstract__factory {
  static readonly abi = _abi;
  static createInterface(): PauseAbstractInterface {
    return new Interface(_abi) as PauseAbstractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PauseAbstract {
    return new Contract(address, _abi, runner) as unknown as PauseAbstract;
  }
}
