/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Changelog } from "./Changelog";
export type { DssExec } from "./DssExec";
export type { PauseAbstract } from "./PauseAbstract";
export type { SpellAction } from "./SpellAction";
