/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PauseAbstractInterface extends Interface {
  getFunction(nameOrSignature: "delay" | "exec" | "plot"): FunctionFragment;

  encodeFunctionData(functionFragment: "delay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "exec",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "plot",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "delay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plot", data: BytesLike): Result;
}

export interface PauseAbstract extends BaseContract {
  connect(runner?: ContractRunner | null): PauseAbstract;
  waitForDeployment(): Promise<this>;

  interface: PauseAbstractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delay: TypedContractMethod<[], [bigint], "view">;

  exec: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BytesLike, arg3: BigNumberish],
    [string],
    "nonpayable"
  >;

  plot: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BytesLike, arg3: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "exec"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BytesLike, arg3: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "plot"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike, arg2: BytesLike, arg3: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
