/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CurveLPOracle } from "./CurveLPOracle";
export type { CurvePoolLike } from "./CurvePoolLike";
export type { OracleLike } from "./OracleLike";
export type { TokenLike } from "./TokenLike";
