/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dssExecSol from "./DssExec.sol";
export type { dssExecSol };
import type * as dssExecLibSol from "./DssExecLib.sol";
export type { dssExecLibSol };
export type { DssAction } from "./DssAction";
