/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ClipLike, ClipLikeInterface } from "../../ilkReg.sol/ClipLike";

const _abi = [
  {
    inputs: [],
    name: "dog",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vat",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ClipLike__factory {
  static readonly abi = _abi;
  static createInterface(): ClipLikeInterface {
    return new Interface(_abi) as ClipLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ClipLike {
    return new Contract(address, _abi, runner) as unknown as ClipLike;
  }
}
