/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Authorizable,
  AuthorizableInterface,
} from "../../../src/DssExecLib.sol/Authorizable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "deny",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "rely",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "setAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Authorizable__factory {
  static readonly abi = _abi;
  static createInterface(): AuthorizableInterface {
    return new Interface(_abi) as AuthorizableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Authorizable {
    return new Contract(address, _abi, runner) as unknown as Authorizable;
  }
}
