/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RegistryLike,
  RegistryLikeInterface,
} from "../../../src/DssExecLib.sol/RegistryLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "xlip",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RegistryLike__factory {
  static readonly abi = _abi;
  static createInterface(): RegistryLikeInterface {
    return new Interface(_abi) as RegistryLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RegistryLike {
    return new Contract(address, _abi, runner) as unknown as RegistryLike;
  }
}
