/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DSAuth } from "./DSAuth";
export type { DSAuthEvents } from "./DSAuthEvents";
export type { DSAuthority } from "./DSAuthority";
export type { DSNote } from "./DSNote";
export type { DSPause } from "./DSPause";
export type { DSPauseProxy } from "./DSPauseProxy";
