/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ClipLikeInterface extends Interface {
  getFunction(nameOrSignature: "sales" | "yank"): FunctionFragment;

  encodeFunctionData(functionFragment: "sales", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "yank", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "sales", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yank", data: BytesLike): Result;
}

export interface ClipLike extends BaseContract {
  connect(runner?: ContractRunner | null): ClipLike;
  waitForDeployment(): Promise<this>;

  interface: ClipLikeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sales: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint, bigint] & {
        pos: bigint;
        tab: bigint;
        lot: bigint;
        usr: string;
        tic: bigint;
        top: bigint;
      }
    ],
    "view"
  >;

  yank: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sales"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint, bigint] & {
        pos: bigint;
        tab: bigint;
        lot: bigint;
        usr: string;
        tic: bigint;
        top: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "yank"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  filters: {};
}
