/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CatLike } from "./CatLike";
export type { ClipLike } from "./ClipLike";
export type { CureLike } from "./CureLike";
export type { DogLike } from "./DogLike";
export type { End } from "./End";
export type { FlipLike } from "./FlipLike";
export type { PipLike } from "./PipLike";
export type { PotLike } from "./PotLike";
export type { SpotLike } from "./SpotLike";
export type { VatLike } from "./VatLike";
export type { VowLike } from "./VowLike";
