/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Cat } from "./Cat";
export type { Kicker } from "./Kicker";
export type { VatLike } from "./VatLike";
export type { VowLike } from "./VowLike";
