/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPulsexV1OracleFactory,
  IPulsexV1OracleFactoryInterface,
} from "../../DaiOracle.sol/IPulsexV1OracleFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pair",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    name: "quote",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPulsexV1OracleFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPulsexV1OracleFactoryInterface {
    return new Interface(_abi) as IPulsexV1OracleFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPulsexV1OracleFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPulsexV1OracleFactory;
  }
}
