/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ChainlogLikeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAddress"
      | "removeAddress"
      | "setAddress"
      | "setIPFS"
      | "setSha256sum"
      | "setVersion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setIPFS", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSha256sum",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setVersion", values: [string]): string;

  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setIPFS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSha256sum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVersion", data: BytesLike): Result;
}

export interface ChainlogLike extends BaseContract {
  connect(runner?: ContractRunner | null): ChainlogLike;
  waitForDeployment(): Promise<this>;

  interface: ChainlogLikeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAddress: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  removeAddress: TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;

  setAddress: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [void],
    "nonpayable"
  >;

  setIPFS: TypedContractMethod<[arg0: string], [void], "nonpayable">;

  setSha256sum: TypedContractMethod<[arg0: string], [void], "nonpayable">;

  setVersion: TypedContractMethod<[arg0: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "removeAddress"
  ): TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIPFS"
  ): TypedContractMethod<[arg0: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSha256sum"
  ): TypedContractMethod<[arg0: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVersion"
  ): TypedContractMethod<[arg0: string], [void], "nonpayable">;

  filters: {};
}
