/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DrippableInterface extends Interface {
  getFunction(nameOrSignature: "drip(bytes32)" | "drip()"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "drip(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "drip()", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "drip(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drip()", data: BytesLike): Result;
}

export interface Drippable extends BaseContract {
  connect(runner?: ContractRunner | null): Drippable;
  waitForDeployment(): Promise<this>;

  interface: DrippableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "drip(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "nonpayable"
  >;

  "drip()": TypedContractMethod<[], [bigint], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "drip(bytes32)"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "drip()"
  ): TypedContractMethod<[], [bigint], "nonpayable">;

  filters: {};
}
