/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LerpFactoryLikeInterface extends Interface {
  getFunction(nameOrSignature: "newIlkLerp" | "newLerp"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "newIlkLerp",
    values: [
      BytesLike,
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "newLerp",
    values: [
      BytesLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "newIlkLerp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newLerp", data: BytesLike): Result;
}

export interface LerpFactoryLike extends BaseContract {
  connect(runner?: ContractRunner | null): LerpFactoryLike;
  waitForDeployment(): Promise<this>;

  interface: LerpFactoryLikeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  newIlkLerp: TypedContractMethod<
    [
      name_: BytesLike,
      target_: AddressLike,
      ilk_: BytesLike,
      what_: BytesLike,
      startTime_: BigNumberish,
      start_: BigNumberish,
      end_: BigNumberish,
      duration_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  newLerp: TypedContractMethod<
    [
      name_: BytesLike,
      target_: AddressLike,
      what_: BytesLike,
      startTime_: BigNumberish,
      start_: BigNumberish,
      end_: BigNumberish,
      duration_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "newIlkLerp"
  ): TypedContractMethod<
    [
      name_: BytesLike,
      target_: AddressLike,
      ilk_: BytesLike,
      what_: BytesLike,
      startTime_: BigNumberish,
      start_: BigNumberish,
      end_: BigNumberish,
      duration_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "newLerp"
  ): TypedContractMethod<
    [
      name_: BytesLike,
      target_: AddressLike,
      what_: BytesLike,
      startTime_: BigNumberish,
      start_: BigNumberish,
      end_: BigNumberish,
      duration_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
