/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { CureLike, CureLikeInterface } from "../../end.sol/CureLike";

const _abi = [
  {
    inputs: [],
    name: "cage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tell",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CureLike__factory {
  static readonly abi = _abi;
  static createInterface(): CureLikeInterface {
    return new Interface(_abi) as CureLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CureLike {
    return new Contract(address, _abi, runner) as unknown as CureLike;
  }
}
