/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { FlipLike, FlipLikeInterface } from "../../end.sol/FlipLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "bids",
    outputs: [
      {
        internalType: "uint256",
        name: "bid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lot",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "guy",
        type: "address",
      },
      {
        internalType: "uint48",
        name: "tic",
        type: "uint48",
      },
      {
        internalType: "uint48",
        name: "end",
        type: "uint48",
      },
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "address",
        name: "gal",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tab",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "yank",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class FlipLike__factory {
  static readonly abi = _abi;
  static createInterface(): FlipLikeInterface {
    return new Interface(_abi) as FlipLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): FlipLike {
    return new Contract(address, _abi, runner) as unknown as FlipLike;
  }
}
